# syntax=docker/dockerfile:1
FROM debian:buster-slim
ENV TERM=xterm

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies
RUN apt-get -qq update \
  && DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes --no-install-recommends \
  ca-certificates curl 'sudo' \
  && curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | DEBIAN_FRONTEND=noninteractive xargs apt-get -qq install --no-install-recommends \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Download and execute the script
RUN /bin/bash -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
