# syntax=docker/dockerfile:1
# Alpine is a lean, efficiency-focused Linux distribution.
# This Dockerfile is ideal for creating lightweight, resource-efficient containers.
FROM alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
ENV TERM=xterm

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install dependencies
RUN apk --no-cache add coreutils curl \
  && curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | awk '{if ($0 == "netcat") print "netcat-openbsd"; else print $0;}' \
  | xargs apk --no-cache add

# Download and execute the script
RUN /bin/bash -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
