# This is the configuration file for the pyspelling spell check job in the Validation CI workflow.

matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - resources/data/pyspelling.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'README.md'
  - '.github/ISSUE_TEMPLATE/*.md'
  - 'docs/CODE_OF_CONDUCT.MD'
  - 'docs/CONTRIBUTING.MD'
  - 'docs/SECURITY.MD'
  - 'docs/lightning.MD'
  - 'docs/usetor.MD'
  default_encoding: utf-8
