#!/bin/sh
#
# A minimally-interactive script for launching a Bitcoin Core node
set -o errexit
set -o nounset

check_dpkg_lock() {
  if fuser /var/lib/dpkg/lock > /dev/null 2>&1 || fuser /var/lib/dpkg/lock-frontend > /dev/null 2>&1; then
    handle_error 'Debian package manager (dpkg) is locked by another process. Try running: ps aux | grep -i apt'
  fi
}

check_internet() {
  check_int_address=$1
  check_int_port="443"
  check_int_timeout="10"
  curl --silent --output /dev/null --connect-timeout "${check_int_timeout}" https://"${check_int_address}:${check_int_port}"
}

get_free_space_in_mib() {
  if [ "$(uname -s)" = "Darwin" ]; then
    /bin/df -m "${HOME}" | awk '{print $4}' | sed 1d
  else
    df --output=avail --block-size="1MiB" "${HOME}" | sed 1d
  fi
}

get_memory_metric_in_mib() (
  metric_to_query="$1"
  awk -v metric="${metric_to_query}" \
    -v kib_mib_factor="${KIB_TO_MIB}" \
    '$0 ~ metric { printf "%d \n", $2 / kib_mib_factor }' /proc/meminfo
)

get_os_release_type() (
  if [ "$(uname -s)" = "Darwin" ]; then
    printf '%s\n' "Darwin"
  else
    os_release_id_like=$(grep "^ID_LIKE=" /etc/os-release | cut -d= -f2)
    os_release_id=$(grep "^ID=" /etc/os-release | cut -d= -f2)

    if [ -n "${os_release_id_like}" ] || [ -n "${os_release_id}" ]; then
      printf '%s\n' "${os_release_id_like:-${os_release_id}}"
    else
      handle_error "Failed to determine OS release type"
    fi
  fi
)

install_dependencies() {
  stderr_install_log_file="${temp_directory}/stderr_install.log"
  printf '%s\n' "${dependencies}" | xargs sudo "$@" 2> "${stderr_install_log_file}"
  grep -v \
    -e "apt-utils" \
    -e "skipping" \
    "${stderr_install_log_file}" >&2 || true
  rm "${stderr_install_log_file}"
}

install_dependencies_aptget() {
  check_dpkg_lock
  install_dependencies DEBIAN_FRONTEND=noninteractive apt-get -qq install --assume-yes --no-install-recommends > /dev/null
}

install_dependencies_dnf() {
  install_dependencies dnf --assumeyes --quiet install > /dev/null
}

install_dependencies_apk() {
  install_dependencies apk --quiet add
}

install_dependencies_pacman() {
  install_dependencies pacman -Syu --needed --noconfirm --quiet > dev/null
}

install_dependencies_zypper() {
  install_dependencies zypper --non-interactive --quiet install > /dev/null
}

install_updates_aptget() {
  check_dpkg_lock
  stderr_install_log_file="${temp_directory}/stderr_install.log"
  sudo apt-get -qq update && sudo NEEDRESTART_MODE=a apt-get -qq dist-upgrade --assume-yes > /dev/null 2> "${stderr_install_log_file}"
  grep -v "apt-utils" "${stderr_install_log_file}" >&2 || true
  rm "${stderr_install_log_file}"
}

install_updates_dnf() {
  sudo dnf --assumeyes --quiet upgrade > /dev/null
}

install_updates_apk() {
  apk update --quiet && apk upgrade --quiet
}

install_updates_pacman() {
  sudo pacman -Syu --noconfirm --quiet > /dev/null
}

install_updates_zypper() {
  sudo zypper --non-interactive --quiet dist-upgrade > /dev/null
}

is_running_in_ci() {
  if [ "${CI:-false}" = "true" ]; then
    return 0
  else
    return 1 #1=false
  fi
}

is_running_in_container() {
  if [ -f /proc/1/cgroup ] && [ "$(grep -c 'docker\|lxc\|actions_job' /proc/1/cgroup)" -gt 0 ]; then
    return 0
  elif [ -f /proc/1/mountinfo ] && [ "$(grep -c 'docker\|lxc\|actions_job' /proc/1/mountinfo)" -gt 0 ]; then
    return 0
  else
    return 1 #1=false
  fi
}

set_bitcoin_core_option() (
  option="$1"
  value="$2"
  if [ -f "${bitcoin_core_config_file:?}" ]; then
    sed -i.bak "/^${option}=/d" "${bitcoin_core_config_file:?}"
    rm "${bitcoin_core_config_file:?}.bak"
  else
    install -m 600 /dev/null "${bitcoin_core_config_file:?}"
  fi
  printf '%s\n' "${option}=${value}" >> "${bitcoin_core_config_file:?}"
)

# This function sets a Bitcoin Core option in the configuration file if it's not already set.
set_if_unset_bitcoin_core_option() (
  option="$1"
  value="$2"
  if [ ! -f "${bitcoin_core_config_file:?}" ]; then
    install -m 600 /dev/null "${bitcoin_core_config_file:?}"
  fi
  if [ "$(grep -c -i "^${option}=" "${bitcoin_core_config_file:?}")" = "0" ]; then
    printf '%s\n' "${option}=${value}" >> "${bitcoin_core_config_file:?}"
  fi
)

log_error() {
  printf '\n%s\n' "[$(date +'%Y-%m-%dT%H:%M:%S')] ERROR: $*" >&2
}

# shellcheck disable=SC2317
handle_exit() {
  [ -n "${temp_directory:-}" ] && rm -rf -- "${temp_directory:?}"/
}

# shellcheck disable=SC2317
handle_error() {
  log_error "Failed to run line $1."
  handle_exit
  exit 1
}

# shellcheck disable=SC2317
handle_sigint() {
  printf '\n%s\n' "Detected Ctrl+C. Exiting."
  handle_exit
  exit 0
}

print_help() {
  printf '%s\n\n' "Usage: $0 [options]"
  printf '%s\n' "Options:"
  printf '%s\n' "-h, --help         Display this help message"
  printf '%s\n' "-u, --unattended   Run in unattended mode"
}

temp_directory=""
unattended=false
prune_value="-1"

while [ $# -gt 0 ]; do
  case "$1" in
  -c | --compile)
    compile_bitcoin="true"
    shift
    ;;
  -h | --help)
    print_help
    exit 0
    ;;
  -p | --prune)
    if [ $# -eq 1 ]; then
      handle_error "-p/--prune requires an argument"
    fi
    case $2 in
    *[!0-9]*) # if $2 contains any non-numeric characters
      handle_error "The prune value '$2' must be a positive integer or zero to disable pruning"
      ;;
    *) ;;
    esac
    if [ "$2" -gt 0 ] && [ "$2" -lt "550" ]; then
      handle_error "The prune value '$2' must be at least 550 (MiB) or zero to disable pruning"
    fi
    prune_value="$2"
    shift 2
    ;;
  -u | --unattended)
    unattended=true
    shift
    ;;
  *)
    printf '%s\n%s\n' "Error: '$1' is invalid." "Use -h or --help for available options."
    exit 1
    ;;
  esac
done

temp_directory="$(mktemp -d)"

trap 'if [ $? -eq 0 ]; then handle_exit; else handle_error ${LINENO:-}; fi' EXIT
trap handle_sigint INT

readonly BYTES_TO_KIB=1024
readonly KIB_TO_MIB="${BYTES_TO_KIB}"
readonly MIB_TO_GIB="${BYTES_TO_KIB}"

target_bitcoin_version="26.1"
target_bitcoin_architecture="$(uname -m)"
user_data_dir="${XDG_DATA_HOME:-${HOME}/.local/share}"
shortcut_image_file="${user_data_dir}/images/bitcoin.png"
shortcut_image_source="https://github.com/bitcoin-tools/nodebuilder/raw/master/data/bitcoin.png"

if is_running_in_container; then
  printf '%s\n' "Detected: running in a container."
fi

if ! command -v sudo > /dev/null 2>&1; then
  handle_error "The dependency 'sudo' is not installed."
elif is_running_in_ci ||
  is_running_in_container ||
  sudo --validate --noninteractive > /dev/null 2>&1; then
  :
else
  printf '%s\n' "Please enter your sudo password if requested."
  sudo --validate
fi

clear
case "$(uname -s)" in
Linux)
  target_bitcoin_operating_system="linux-gnu"
  bitcoin_core_data_dir="${HOME}/.bitcoin"
  printf '%s\n%s' "Detected: running on Linux." "Checking for internet... "
  ( (check_internet 1.1.1.1 ||
    check_internet 1.1.0.0 ||
    check_internet 9.9.9.9 ||
    check_internet 9.9.9.11) &&
    check_internet bitcoincore.org) ||
    handle_error "Check for active internet failed."
  printf '%s\n%s' "ok." "Performing a system upgrade... "
  case "$(get_os_release_type)" in
  alpine)
    install_updates_apk
    ;;
  debian | ubuntu)
    install_updates_aptget
    ;;
  fedora | rhel)
    install_updates_dnf
    ;;
  arch | manjaro)
    install_updates_pacman
    ;;
  suse | *opensuse*)
    install_updates_zypper
    ;;
  *)
    if command -v apk > /dev/null; then
      install_updates_apk
    elif command -v apt-get > /dev/null; then
      install_updates_aptget
    elif command -v dnf > /dev/null; then
      install_updates_dnf
    elif command -v pacman > /dev/null; then
      install_updates_pacman
    elif command -v zypper > /dev/null; then
      install_updates_zypper
    else
      handle_error "This version of Linux is not supported."
    fi
    ;;
  esac

  # Stop running if the Docker container base image is outdated
  if [ -f /var/run/reboot-required ] && is_running_in_container; then
    handle_error "The Docker base image is outdated. Please open an issue at github.com/bitcoin-tools/nodebuilder."
  # Reboot the system unless it's running in CI/CD
  elif [ -f /var/run/reboot-required ] && ! is_running_in_ci; then
    printf '\n%s\n%s\n' "REBOOT REQUIRED to upgrade the following:" "$(cat /var/run/reboot-required.pkgs)"
    if [ "${unattended}" = false ]; then
      printf '\n%s' "PRESS ENTER to reboot or press Ctrl+C to exit... "
      read -r _
      printf '\n'
    fi
    printf '%s\n' "Rebooting."
    sudo reboot
    exit 0
  fi
  printf '%s\n' "ok."

  printf '%s' "Checking for dependencies... "
  dependencies_url="https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt"
  dependencies=$(curl --fail --silent --show-error --location --retry 5 --retry-delay 10 "${dependencies_url}")
  [ -z "$dependencies" ] && handle_error "The list of dependencies is empty."
  case "$(get_os_release_type)" in
  alpine)
    install_dependencies_apk
    ;;
  debian | ubuntu)
    install_dependencies_aptget
    ;;
  fedora | rhel)
    install_dependencies_dnf
    ;;
  arch | manjaro)
    install_dependencies_pacman
    ;;
  suse | *opensuse*)
    install_dependencies_zypper
    ;;
  *)
    install_command_function=""
    for package_manager in \
      apk \
      apt-get \
      dnf \
      pacman \
      zypper; do
      if command -v "${package_manager}" > /dev/null; then
        install_command_function="install_dependencies_$(echo "${package_manager}" | tr -d '-')"
        break
      fi
    done

    if [ -n "${install_command_function}" ]; then
      "${install_command_function}"
    else
      handle_error "This version of Linux is not supported."
    fi
    ;;
  esac
  printf '%s\n' "ok."
  ;;
Darwin)
  target_bitcoin_operating_system="apple-darwin"
  bitcoin_core_data_dir="${HOME}/Library/Application Support/Bitcoin"
  printf '%s\n%s' "Detected: running on macOS." "Checking for internet... "
  ( (check_internet 1.1.1.1 ||
    check_internet 1.1.0.0 ||
    check_internet 9.9.9.9 ||
    check_internet 9.9.9.11) &&
    check_internet bitcoincore.org) ||
    handle_error "Check for active internet failed."
  printf '%s\n' "ok."
  if ! command -v git > /dev/null 2>&1; then
    printf '%s' "Installing git via the Xcode Command Line Tools... "
    # These steps were taken from https://github.com/Homebrew/install/blob/aceed88a4a062e2b41dc40a7428c71309fce14c9/install.sh#L831
    # TODO: find a way to install only the git binary, not all the Xcode tools. Unattended xcode tools installation shouldn't take 20+ lines of code
    sudo touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    clt_label_command="/usr/sbin/softwareupdate -l | grep -B 1 -E 'Command Line Tools' | awk -F'*' '/^ *\\*/ {print \$2}' | sed -e 's/^ *Label: //' -e 's/^ *//' | sort -V | tail -n1 | tr -d '\n'"
    clt_label="$(/bin/sh -c "${clt_label_command}")"
    if [ -n "${clt_label}" ]; then
      sudo /usr/sbin/softwareupdate -i "${clt_label}" > /dev/null
    else
      handle_error "Failed to install git, cannot find a compatible Xcode Command Line Tools package."
    fi
    sudo rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress

    if command -v git > /dev/null 2>&1; then
      printf '%s\n' "ok."
    else
      if [ "${unattended}" = true ]; then
        printf '\n%s\n' "ERROR: Failed to install Xcode. Try re-running without -u/--unattended."
        exit 1
      fi

      printf '%s\n%s\n' "failed." "Installing the Command Line Tools (expect a GUI popup)."
      /usr/bin/xcode-select --install
      printf '%s\n' "PRESS ENTER when the installation has completed."
      read -r _
      if ! command -v git > /dev/null 2>&1; then
        handle_error "Failed to install git via the Xcode Command Line Tools."
      fi
    fi
  fi
  ;;
MINGW*)
  handle_error "Windows is not supported. Instead, use WSL (Windows Subsystem for Linux)."
  ;;
*)
  handle_error "Your operating system is not supported."
  ;;
esac

printf '%s' "Checking for Bitcoin Core ${target_bitcoin_version}... "
if command -v bitcoind > /dev/null 2>&1; then
  current_bitcoin_version="$(bitcoind --version 2> /dev/null | head -1 | cut -c23-)"
else
  current_bitcoin_version=""
fi

# If bitcoin target version is like 'xx.yy', pad it as 'xx.yy.0'
case "${target_bitcoin_version}" in
*[.]*[.]*)
  target_bitcoin_version_padded="${target_bitcoin_version}"
  ;;
*)
  target_bitcoin_version_padded="${target_bitcoin_version}.0"
  ;;
esac

if [ "${current_bitcoin_version}" = "${target_bitcoin_version_padded}" ]; then
  printf '%s\n' "found."
elif [ "${compile_bitcoin:-"false"}" = "true" ] || [ "$(get_os_release_type)" = "alpine" ]; then
  compile_directory="${temp_directory}/compile_bitcoin"
  stderr_compile_log_file="${temp_directory}/stderr_install.log"
  printf '%s\n  %s' "not found." "Installing build dependencies... "
  case "$(get_os_release_type)" in
  alpine)
    echo "install_build_dependencies_apk()"
    apk --quiet add alpine-sdk libffi-dev autoconf automake db-dev boost boost-dev libtool libevent-dev |
      grep -v "ICU with non-English locales" -A2 -B1 || true
    ;;
  debian | ubuntu)
    echo "install_build_dependencies_aptget()"
    DEBIAN_FRONTEND=noninteractive sudo apt-get -qq install --assume-yes --no-install-recommends build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev libsqlite3-dev qtbase5-dev qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev > /dev/null
    ;;
  fedora | rhel)
    echo "install_build_dependencies_dnf()"
    sudo dnf install gcc-c++ libtool make autoconf automake python3 libevent-devel boost-devel sqlite-devel qt5-qttools-devel qt5-qtbase-devel qt5-qtwayland qrencode-devel
    ;;
  arch | manjaro)
    echo "install_build_dependencies_pacman()"
    ;;
  suse | *opensuse*)
    echo "install_build_dependencies_zypper()"
    ;;
  Darwin)
    # TODO: install brew
    brew install automake libtool boost pkg-config libevent berkeley-db@4 python qt@5 qrencode
    ;;
  *)
    install_command_function=""
    for package_manager in \
      apk \
      apt-get \
      dnf \
      pacman \
      zypper; do
      if command -v "${package_manager}" > /dev/null; then
        install_build_command_function="install_build_dependencies_$(echo "${package_manager}" | tr -d '-')"
        break
      fi
    done
    #if [ -n "${install_build_command_function}" ]; then
    #  "${install_command_function}"
    #else
    #  handle_error "This version of Linux is not supported."
    #fi
    echo "DEBUG ONLY The build build command function to be called is ${install_build_command_function}()"
    ;;
  esac
  printf '%s\n  %s' "ok." "Downloading Bitcoin source code... "
  git clone --branch "v${target_bitcoin_version}" --single-branch --depth 1 --quiet -c advice.detachedHead=false https://github.com/bitcoin/bitcoin.git "${compile_directory}"
  cd "${compile_directory}"/
  printf '%s\n  %s' "ok." "Analyzing hardware confgiruation... "
  ./autogen.sh > /dev/null 2> "${stderr_compile_log_file}"
  grep -v "build-aux" "${stderr_compile_log_file}" >&2 || true
  printf '%s\n  %s' "ok." "Configuring the build environment... "
  ./configure --without-bdb --enable-suppress-external-warnings > /dev/null 2> "${stderr_compile_log_file}"
  grep -v \
    -e "libzmq" \
    "${stderr_compile_log_file}" >&2 || true
  printf '%s\n  %s' "ok." "Building (please wait)... "
  make --jobs "$(($(nproc) + 1))" > /dev/null
  printf '%s\n  %s' "ok." "Checking (please wait)... "
  make --jobs "$(($(nproc) + 1))" check > /dev/null 2> "${stderr_compile_log_file}"
  grep -v "Ran 3 tests in " -A1 -B2 "${stderr_compile_log_file}" >&2 || true
  printf '%s\n  %s' "ok." "Installing Bitcoin... "
  make install > /dev/null 2>&1 || sudo make install > /dev/null
  cd "${temp_directory}"/
  rm "${stderr_compile_log_file}"
  rm -rf "${compile_directory:?}"/
  current_bitcoin_version="${target_bitcoin_version}"
else
  printf '%s\n' "not found."
  bitcoin_core_extract_dir="${temp_directory}/bitcoin-core"
  bitcoin_install_bin_source="${bitcoin_core_extract_dir}/bin"
  bitcoin_install_lib_source="${bitcoin_core_extract_dir}/lib"
  bitcoin_install_include_source="${bitcoin_core_extract_dir}/include"
  bitcoin_install_man_source="${bitcoin_core_extract_dir}/share/man/man1"
  bitcoin_install_destination="/usr/local"
  bitcoin_install_bin_destination="${bitcoin_install_destination}/bin"
  bitcoin_install_lib_destination="${bitcoin_install_destination}/lib"
  bitcoin_install_include_destination="${bitcoin_install_destination}/include"
  bitcoin_install_man_destination="${bitcoin_install_destination}/share/man/man1"

  bitcoin_tarball_filename="bitcoin-${target_bitcoin_version}-${target_bitcoin_architecture}-${target_bitcoin_operating_system}.tar.gz"
  bitcoin_tarball_destination_file="${HOME}/Downloads/${bitcoin_tarball_filename}"

  if ! [ -f "${bitcoin_tarball_destination_file}" ]; then
    bitcoin_source="https://bitcoincore.org/bin/bitcoin-core-${target_bitcoin_version}"
    bitcoin_tarball_file_source="${bitcoin_source}/${bitcoin_tarball_filename}"
    bitcoin_hash_filename="SHA256SUMS"
    bitcoin_hash_file_source="${bitcoin_source}/${bitcoin_hash_filename}"
    gpg_signatures_filename="SHA256SUMS.asc"
    gpg_signatures_file_source="${bitcoin_source}/${gpg_signatures_filename}"
    gpg_good_signatures_required="7"
    guix_sigs_repo="https://github.com/bitcoin-core/guix.sigs.git"
    bitcoin_tarball_temporary_file="${temp_directory}/${bitcoin_tarball_filename}"
    bitcoin_hash_file="${temp_directory}/${bitcoin_hash_filename}"
    gpg_signatures_file="${temp_directory}/${gpg_signatures_filename}"
    guix_sigs_temporary_dir="${temp_directory}/guix.sigs"
    guix_sigs_destination_dir="${HOME}/Downloads/guix.sigs"
    printf '  %s' "Downloading Bitcoin Core... "
    curl --fail --silent --show-error --location --retry 5 --retry-delay 10 --output "${bitcoin_tarball_temporary_file}" "${bitcoin_tarball_file_source}"
    curl --fail --silent --show-error --location --retry 5 --retry-delay 10 --output "${bitcoin_hash_file}" "${bitcoin_hash_file_source}"
    curl --fail --silent --show-error --location --retry 5 --retry-delay 10 --output "${gpg_signatures_file}" "${gpg_signatures_file_source}"
    printf '%s\n' "ok."

    printf '  %s' "Validating the checksum... "
    cd "${temp_directory}"/
    if command -v sha256sum > /dev/null; then
      sha256_check="$(grep "${bitcoin_tarball_filename}" "${bitcoin_hash_filename}" | sha256sum --check 2> /dev/null)"
    elif command -v shasum > /dev/null; then
      sha256_check="$(grep "${bitcoin_tarball_filename}" "${bitcoin_hash_filename}" | shasum -a 256 --check 2> /dev/null)"
    else
      handle_error "Either 'sha256sum' or 'shasum' must on PATH."
    fi
    cd "${HOME}"/
    case "${sha256_check}" in
    *"OK"*) ;;
    *)
      handle_error "INVALID CHECKSUM. The download has failed. This script cannot continue due to security concerns. Please review the temporary file ${temp_directory}/${bitcoin_hash_file}."
      ;;
    esac
    printf '%s\n' "ok."

    printf '  %s' "Validating the signatures... "
    if [ -d "${guix_sigs_destination_dir}"/ ]; then
      gpg --quiet --import "${guix_sigs_destination_dir}"/builder-keys/*.gpg
    else
      git clone --single-branch --depth 1 --quiet "${guix_sigs_repo}" "${guix_sigs_temporary_dir}"
      gpg --quiet --import "${guix_sigs_temporary_dir}"/builder-keys/*.gpg
    fi
    gpg_good_signature_count=$(gpg --verify "${gpg_signatures_file}" 2>&1 | grep -c "^gpg: Good signature from ")
    if [ "${gpg_good_signature_count}" -ge "${gpg_good_signatures_required}" ]; then
      printf '%s\n' "${gpg_good_signature_count} good."
      [ -d "$(dirname "${bitcoin_tarball_destination_file}")" ] || mkdir -p "$(dirname "${bitcoin_tarball_destination_file}")"
      mv "${bitcoin_tarball_temporary_file}" "${bitcoin_tarball_destination_file}"
      [ -d "${guix_sigs_destination_dir}"/ ] || mv "${guix_sigs_temporary_dir}" "${guix_sigs_destination_dir}"
      rm "${bitcoin_hash_file}"
      rm "${gpg_signatures_file}"
    else
      handle_error "INVALID SIGNATURES. The download has failed. This script cannot continue due to security concerns. Please review the temporary file ${temp_directory}/${gpg_signatures_file}."
    fi
  fi

  printf '  %s' "Extracting Bitcoin Core... "
  [ -d "${bitcoin_core_extract_dir}"/ ] || mkdir "${bitcoin_core_extract_dir}"
  tar -xzf "${bitcoin_tarball_destination_file}" -C "${bitcoin_core_extract_dir}"/ --strip-components=1
  printf '%s\n' "ok."

  printf '  %s' "Running the unit tests... "
  if [ "${target_bitcoin_architecture}" = "arm64" ]; then
    codesign -s - "${bitcoin_install_bin_source}"/test_bitcoin
  fi
  unit_test_response="$("${bitcoin_install_bin_source}"/test_bitcoin 2>&1)"
  case "${unit_test_response}" in
  *"No errors detected"*) ;;
  *)
    printf '%s\n' "\n${unit_test_response}"
    handle_error "Unit tests failed."
    ;;
  esac
  printf '%s\n  %s' "ok." "Installing Bitcoin Core... "
  [ -d "${bitcoin_install_lib_destination}" ] || mkdir -p "${bitcoin_install_lib_destination}" 2> /dev/null || sudo mkdir "${bitcoin_install_lib_destination}" || handle_error "Unable to create directory ${bitcoin_install_lib_destination}."
  case "$(uname -s)" in
  Linux)
    sudo cp "${bitcoin_install_lib_source}"/libbitcoinconsensus.so.0.0.0 "${bitcoin_install_lib_destination}"/libbitcoinconsensus.so.0.0.0
    (cd "${bitcoin_install_lib_destination}"/ && { sudo ln -s -f libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so.0 || { sudo rm -f libbitcoinconsensus.so.0 && sudo ln -s libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so.0; }; })
    (cd "${bitcoin_install_lib_destination}"/ && { sudo ln -s -f libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so || { sudo rm -f libbitcoinconsensus.so && sudo ln -s libbitcoinconsensus.so.0.0.0 libbitcoinconsensus.so; }; })
    PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n "${bitcoin_install_lib_destination}"
    ;;
  Darwin)
    sudo cp "${bitcoin_install_lib_source}"/libbitcoinconsensus.0.dylib "${bitcoin_install_lib_destination}"/libbitcoinconsensus.0.dylib
    (cd "${bitcoin_install_lib_destination}"/ && { sudo ln -s -f libbitcoinconsensus.0.dylib libbitcoinconsensus.dylib || { sudo rm -f libbitcoinconsensus.dylib && sudo ln -s libbitcoinconsensus.0.dylib libbitcoinconsensus.dylib; }; })
    sudo update_dyld_shared_cache

    if [ "${target_bitcoin_architecture}" = "arm64" ]; then
      for bitcoin_executable in bitcoin-cli bitcoin-qt bitcoin-tx bitcoin-util bitcoin-wallet bitcoind; do
        codesign -s - "${bitcoin_install_bin_source}/${bitcoin_executable}"
      done
    fi
    ;;
  esac

  [ -d "${bitcoin_install_bin_destination}" ] || mkdir -p "${bitcoin_install_bin_destination}" 2> /dev/null || sudo mkdir "${bitcoin_install_bin_destination}" || handle_error "Unable to create directory ${bitcoin_install_bin_destination}."
  for bitcoin_executable in bitcoind bitcoin-qt bitcoin-cli bitcoin-tx bitcoin-util bitcoin-wallet test_bitcoin; do
    sudo install -c "${bitcoin_install_bin_source}/${bitcoin_executable}" "${bitcoin_install_bin_destination}/"
  done

  [ -d "${bitcoin_install_include_destination}" ] || mkdir -p "${bitcoin_install_include_destination}" 2> /dev/null || sudo mkdir "${bitcoin_install_include_destination}" || handle_error "Unable to create directory ${bitcoin_install_include_destination}."
  sudo install -c -m 644 "${bitcoin_install_include_source}"/bitcoinconsensus.h "${bitcoin_install_include_destination}/"

  [ -d "${bitcoin_install_man_destination}" ] || mkdir -p "${bitcoin_install_man_destination}" 2> /dev/null || sudo mkdir -p "${bitcoin_install_man_destination}" || handle_error "Unable to create directory ${bitcoin_install_man_destination}."
  for man_page in bitcoind.1 bitcoin-qt.1 bitcoin-cli.1 bitcoin-tx.1 bitcoin-util.1 bitcoin-wallet.1; do
    sudo install -c -m 644 "${bitcoin_install_man_source}/${man_page}" "${bitcoin_install_man_destination}/"
  done
  printf '%s\n' "ok."

  printf '  %s' "Removing installation files... "
  rm -r "${bitcoin_core_extract_dir:?}/"
  rm -r "${temp_directory:?}/"
  printf '%s\n' "ok."
fi

if [ "$(uname -s)" != "Darwin" ]; then
  printf '%s' "Creating application shortcuts... "
  desktop_path="${HOME}/Desktop"
  applications_path="${user_data_dir}/applications"
  shortcut_filename="bitcoin_core.desktop"

  [ -d "$(dirname "${shortcut_image_file}")" ] || mkdir -p "$(dirname "${shortcut_image_file}")"
  [ -f "${shortcut_image_file}" ] || curl --silent --show-error --location --fail --output "${shortcut_image_file}" "${shortcut_image_source}"

  ## Create .desktop on the user's Desktop and "Show Applications" directories
  [ -d "${desktop_path}" ] || mkdir -p "${desktop_path}"
  [ -d "${applications_path}" ] || mkdir -p "${applications_path}"
  cat << EOF | tee "${applications_path}"/"${shortcut_filename}" > "${desktop_path}"/"${shortcut_filename}"
[Desktop Entry]
Name=Bitcoin Core
Comment=Launch Bitcoin Core
Exec=bitcoin-qt %u || bitcoind --daemonwait
Icon=${shortcut_image_file}
Terminal=false
StartupWMClass=Bitcoin Core
Type=Application
Categories=Application;
MimeType=application/bitcoin-paymentrequest;application/bitcoin-payment;application/bitcoin-paymentack;x-scheme-handler/bitcoin;
EOF
  chmod u+x "${applications_path}"/"${shortcut_filename}"
  chmod u+x "${desktop_path}"/"${shortcut_filename}"
  ## Make the desktop shortcut trusted
  if is_running_in_ci || is_running_in_container; then
    :
  else
    gio set "${desktop_path}"/"${shortcut_filename}" "metadata::trusted" true
  fi
  printf '%s\n' "ok."
fi

bitcoin_core_config_file="${bitcoin_core_data_dir}/bitcoin.conf"
if [ ! -f "${bitcoin_core_config_file}" ]; then
  printf '%s' "Setting the default node behavior... "
  [ -d "${bitcoin_core_data_dir}"/ ] || mkdir "${bitcoin_core_data_dir}"/
  set_bitcoin_core_option "server" "1"
  set_bitcoin_core_option "mempoolfullrbf" "1"
  set_bitcoin_core_option "v2transport" "1"
  printf '%s\n' "ok."
fi

case "$(uname -s)" in
Darwin) ;; #TODO: Add macOS memory check
*)
  printf '%s' "Checking the memory on your system... "
  physical_memory_total_in_mib="$(get_memory_metric_in_mib 'MemTotal')"
  physical_memory_free_in_mib="$(get_memory_metric_in_mib 'MemAvailable')"
  swap_memory_total_in_mib="$(get_memory_metric_in_mib 'SwapTotal')"
  swap_memory_free_in_mib="$(get_memory_metric_in_mib 'SwapFree')"
  memory_total_in_mib=$((physical_memory_total_in_mib + swap_memory_total_in_mib))
  memory_free_in_mib=$((physical_memory_free_in_mib + swap_memory_free_in_mib))
  printf '%0.1f GiB free of %0.1f GiB.\n' \
    "$(awk -v mem_free_mib="${memory_free_in_mib}" -v mib_gib_factor="${MIB_TO_GIB}" 'BEGIN{printf "%f\n", mem_free_mib / mib_gib_factor}')" \
    "$(awk -v mem_total_mib="${memory_total_in_mib}" -v mib_gib_factor="${MIB_TO_GIB}" 'BEGIN{printf "%f\n", mem_total_mib / mib_gib_factor}')"

  if [ "${memory_total_in_mib}" -le $((2 * MIB_TO_GIB)) ] || [ "${memory_free_in_mib}" -le "64" ]; then
    printf '%s' "Configuring for minimal memory usage... "
    set_if_unset_bitcoin_core_option "dbcache" "4"
    set_if_unset_bitcoin_core_option "maxmempool" "5"
    set_if_unset_bitcoin_core_option "maxconnections" "4"
    [ "$(uname -s)" = "Linux" ] && export MALLOC_ARENA_MAX=1
    printf '%s\n' "ok."
  elif [ "${memory_total_in_mib}" -le $((4 * MIB_TO_GIB)) ] || [ "${memory_free_in_mib}" -le "128" ]; then
    printf '%s' "Configuring for reduced memory usage... "
    set_if_unset_bitcoin_core_option "dbcache" "100"
    set_if_unset_bitcoin_core_option "maxmempool" "50"
    set_if_unset_bitcoin_core_option "maxconnections" "10"
    [ "$(uname -s)" = "Linux" ] && export MALLOC_ARENA_MAX=1
    printf '%s\n' "ok."
  elif [ "${memory_total_in_mib}" -le $((8 * MIB_TO_GIB)) ] || [ "${memory_free_in_mib}" -le "256" ]; then
    printf '%s' "Configuring for conservative memory usage... "
    set_if_unset_bitcoin_core_option "dbcache" "225"
    set_if_unset_bitcoin_core_option "maxmempool" "150"
    printf '%s\n' "ok."
  fi
  ;;
esac

printf '%s' "Checking data already synced... "
bitcoin_core_blocks_dir="${bitcoin_core_data_dir}/blocks"
bitcoin_core_chainstate_dir="${bitcoin_core_data_dir}/chainstate"
blocks_size_in_mib="0"
chainstate_size_in_mib="0"
if [ -d "${bitcoin_core_blocks_dir}"/ ]; then
  if [ "$(uname -s)" = "Darwin" ]; then
    blocks_size_in_mib=$(du -d0 -m "${bitcoin_core_blocks_dir}" | cut -f1)
  else
    blocks_size_in_mib=$(du -d0 --block-size="1MiB" "${bitcoin_core_blocks_dir}" | cut -f1)
  fi
fi
if [ -d "${bitcoin_core_chainstate_dir}"/ ]; then
  if [ "$(uname -s)" = "Darwin" ]; then
    chainstate_size_in_mib=$(du -d0 -m "${bitcoin_core_chainstate_dir}" | cut -f1)
  else
    chainstate_size_in_mib=$(du -d0 --block-size="1MiB" "${bitcoin_core_chainstate_dir}" | cut -f1)
  fi
fi
data_already_synced_in_mib=$((blocks_size_in_mib + chainstate_size_in_mib))
printf '%s\n' "$((data_already_synced_in_mib / MIB_TO_GIB)) GiB."

printf '%s' "Checking free space in home directory... "
free_space_in_mib="$(get_free_space_in_mib)"
printf '%s\n' "$((free_space_in_mib / MIB_TO_GIB)) GiB."

## This constant will need to be adjusted over time as the chain grows
## or need to find how to generate this dynamically in a trustless way.
## The lower this number is, the more likely disk space errors during IBD.
## The higher this number is, the more likely a node will be to prune.
## The sweet spot is about 50 to 100 GB more than the size of blocks/ + chainstate/,
## which, as of June 2023, is around 522 GiB.
archival_node_required_disk_in_gib="686"
archival_node_required_disk_in_mib=$((archival_node_required_disk_in_gib * MIB_TO_GIB))

# check if the user wants to disable pruning
if [ "${prune_value}" -eq 0 ]; then
  if [ "$((data_already_synced_in_mib + free_space_in_mib))" -lt "${archival_node_required_disk_in_mib}" ]; then
    handle_error "Not enough storage to disable pruning. Free up ${archival_node_required_disk_in_gib} GiB or use a positive value less than $((data_already_synced_in_mib + free_space_in_mib)) \(MiB\)."
  fi
  printf '  %s' "Configuring with the disabled prune option... "
  set_bitcoin_core_option "prune" "${prune_value}"
  printf '%s\n' "ok."
# check if the user passed in a prune value
elif [ "${prune_value}" -gt 0 ]; then
  if [ "$((data_already_synced_in_mib + free_space_in_mib))" -lt "${prune_value}" ]; then
    handle_error "Prune value ${prune_value} too large. Run without setting prune or use a value less than $((data_already_synced_in_mib + free_space_in_mib)) \(MiB\)."
  fi
  printf '  %s' "Configuring with the ${prune_value} MiB prune option... "
  set_bitcoin_core_option "prune" "${prune_value}"
  printf '%s\n' "ok."
# check that a prune value doesn't already exist in the config file
elif [ "$(grep -c -i "^prune=" "${bitcoin_core_config_file}")" = "0" ]; then
  if [ "${free_space_in_mib}" -ge $((archival_node_required_disk_in_mib - data_already_synced_in_mib)) ]; then
    printf '  %s\n' "Your node will run as an unpruned full node."
    set_bitcoin_core_option "prune" "0"
  elif [ "${free_space_in_mib}" -lt $((archival_node_required_disk_in_mib / 80 - data_already_synced_in_mib)) ]; then
    handle_error "You are too low on disk space to run Bitcoin Core."
  else
    if [ "${free_space_in_mib}" -lt $((archival_node_required_disk_in_mib / 40 - data_already_synced_in_mib)) ]; then
      printf '  %s\n  %s\n' "Your disk space is low." "Setting blocks-only mode and the minimum 0.55 GiB prune."
      set_bitcoin_core_option "blocksonly" "1"
      prune_amount_in_mib="550"
    else
      if [ "${free_space_in_mib}" -lt $((archival_node_required_disk_in_mib / 12 - data_already_synced_in_mib)) ]; then
        prune_ratio=20
      elif [ "${free_space_in_mib}" -lt $((archival_node_required_disk_in_mib / 4 - data_already_synced_in_mib)) ]; then
        prune_ratio=40
      elif [ "${free_space_in_mib}" -lt $((archival_node_required_disk_in_mib * 3 / 4 - data_already_synced_in_mib)) ]; then
        prune_ratio=60
      else
        prune_ratio=80
      fi
      prune_amount_in_mib=$((free_space_in_mib * prune_ratio / 100))
      printf '  Pruning to %d GiB (%d%% of the free space).\n  You can change this in ~/.bitcoin/bitcoin.conf.\n' "$((prune_amount_in_mib / MIB_TO_GIB))" "${prune_ratio}"
    fi
    set_bitcoin_core_option "prune" "${prune_amount_in_mib}"
  fi
fi

printf '%s' "Starting Bitcoin Core... "
if is_running_in_ci ||
  is_running_in_container ||
  ! command -v bitcoin-qt > /dev/null 2>&1; then
  bitcoind --daemonwait > /dev/null
elif [ "$(uname -s)" = "Darwin" ]; then
  nohup bitcoin-qt > /dev/null 2>&1 < /dev/null &
else
  setsid bitcoin-qt > /dev/null 2>&1 < /dev/null &
fi

printf '%s\n  %s' "ok." "Checking the RPC status... "
rpc_timeout=60
if ! bitcoin-cli --rpcwait --rpcwaittimeout="${rpc_timeout}" getrpcinfo > /dev/null; then
  handle_error "RPC communication failed after ${rpc_timeout} seconds"
fi
printf '%s\n' "ok."

sleep_time="10"
blockchain_info=$(bitcoin-cli --rpcwait getblockchaininfo)
ibd_status=$(echo "${blockchain_info}" | jq '.initialblockdownload')

if [ "${ibd_status}" = true ]; then
  if ! is_running_in_container; then
    printf '%s' "Disabling system sleep, suspend, and hibernate... "
    if [ "$(uname -s)" = "Darwin" ]; then
      caffeinate -sw "$(cat ~/Library/Application\ Support/Bitcoin/bitcoind.pid)" &
    else
      sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target > /dev/null 2>&1
    fi
    printf '%s\n%s\n%s' \
      "ok." \
      "Close this Terminal window by clicking on the \"X\"." \
      "This screen will refresh in ${sleep_time} seconds."
  fi
  i=1
  while [ "$i" -le 10 ]; do
    sleep 1
    printf '%s' "."
    i=$((i + 1))
  done
  printf '\n'
else
  printf '  %s\n' "Your node has already synced the blockchain."
fi

while [ "${ibd_status}" = true ]; do
  blocks=$(echo "${blockchain_info}" | jq '.blocks')
  headers=$(echo "${blockchain_info}" | jq '.headers')
  last_block_time=$(echo "${blockchain_info}" | jq '.time')
  size_on_disk_in_mib=$(($(echo "${blockchain_info}" | jq '.size_on_disk') / BYTES_TO_KIB / KIB_TO_MIB))
  sync_progress=$(echo "${blockchain_info}" | jq '.verificationprogress')

  # Handle case of early sync by replacing scientific notation with decimal
  if [ "$(printf '%s\n' "${sync_progress}" | grep -c -i "e")" -gt 0 ]; then
    sync_progress="0.000000001"
  fi
  sync_progress_percent="$(awk -v prog="${sync_progress}" 'BEGIN{printf "%f\n", prog * 100}')"

  free_space_in_mib=$(get_free_space_in_mib)

  clear
  if [ "${headers}" -eq 0 ]; then
    printf '%s\n' 'Syncing the block headers (first pass).'
  elif [ "${blocks}" -eq 0 ]; then
    printf '%s\n' 'Syncing the block headers (second pass).'
    printf 'Headers synced:     %d\n' "${headers}"
  else
    printf 'Sync progress:      %.3f %%\n' "${sync_progress_percent}"
    printf 'Blocks remaining:   %d\n' "$((headers - blocks))"

    if [ "$(uname -s)" = "Darwin" ]; then
      printf 'Current chain tip:  %s\n' "$(/bin/date -r "${last_block_time}" | cut -c 5-)"
    else
      printf 'Current chain tip:  %s\n' "$(date -d @"${last_block_time}" | cut -c 5-)"
    fi

    printf '%s' 'Chain sync size:    '
    if [ "${size_on_disk_in_mib}" -gt "${MIB_TO_GIB}" ]; then
      printf '%d GiB\n' "$((size_on_disk_in_mib / MIB_TO_GIB))"
    else
      printf '%d MiB\n' "${size_on_disk_in_mib}"
    fi
  fi

  printf '%s' 'Disk free space:    '
  if [ "${free_space_in_mib}" -gt "${MIB_TO_GIB}" ]; then
    printf '%d GiB\n' "$((free_space_in_mib / MIB_TO_GIB))"
  else
    printf '%d MiB\n' "${free_space_in_mib}"
  fi

  if [ "${size_on_disk_in_mib}" -ge 1 ] && (is_running_in_ci || is_running_in_container); then
    printf '%s\n' "The blockchain download is progressing. Exiting the script."
    exit 0
  fi

  printf '%s\n\n' "Synchronizing can take weeks on a slow connection."
  printf '%s\n' "Close this Terminal window by clicking on the \"X\"."
  printf '%s' "This screen will refresh in ${sleep_time} seconds."
  sleep "${sleep_time}"

  blockchain_info=$(bitcoin-cli --rpcwait getblockchaininfo)
  printf '\n'
  ibd_status=$(echo "${blockchain_info}" | jq '.initialblockdownload')
done

printf '%s\n' "This script has completed successfully."
exit 0
