# syntax=docker/dockerfile:1
# Fedora is known for its proactive security and commitment to open-source software.
# This Dockerfile is a good choice for modern and resource-rich environments.
FROM fedora:39@sha256:61864fd19bbd64d620f338eb11dae9e8759bf7fa97302ac6c43865c48dccd679
ENV TERM=xterm

# Check the current system
RUN grep "VERSION\|ID" /etc/os-release

# Install system updates and dependencies
RUN dnf --assumeyes install git netcat

# Download and execute the script
RUN /bin/bash -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
