# syntax=docker/dockerfile:1
FROM manjarolinux/base:20240227@sha256:369753d82cfddfb500e9ef756334e0323508172c31041ea30501530cb5b24c12
ENV TERM=xterm

# Check the current system
RUN grep "VERSION\|ID" /etc/os-release

# Install system updates and dependencies
RUN pacman -Syu --noconfirm git netcat

# Execute the script
RUN git clone --single-branch --depth 1 https://github.com/bitcoin-tools/nodebuilder.git \
  && cd nodebuilder
COPY nodebuilder /opt/src/scripts/nodebuilder
RUN /bin/bash -c /opt/src/scripts/nodebuilder
