# syntax=docker/dockerfile:1
FROM fedora:39@sha256:61864fd19bbd64d620f338eb11dae9e8759bf7fa97302ac6c43865c48dccd679
ENV TERM=xterm

# Check the current system
RUN grep "VERSION\|ID" /etc/os-release

# Install system updates and dependencies
RUN dnf --assumeyes install git netcat

# Execute the script
RUN git clone --single-branch --depth 1 https://github.com/bitcoin-tools/nodebuilder.git \
  && cd nodebuilder
COPY nodebuilder /opt/src/scripts/nodebuilder
RUN /bin/bash -c /opt/src/scripts/nodebuilder
