# syntax=docker/dockerfile:1
# Alpine Linux is known for its small size and security focus.
# This Dockerfile is a good choice for minimalistic and resource-constrained environments.
FROM alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
ENV TERM=xterm

# Check the current system
RUN grep "VERSION\|ID" /etc/os-release

# Install system updates and dependencies
RUN apk update && apk --no-cache add bash coreutils curl git

# Download and execute the script
RUN /bin/bash -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
