# syntax=docker/dockerfile:1
# Manjaro focuses on user-friendliness and accessibility.
# This Dockerfile is ideal for users who want a balance of control and convenience.
FROM manjarolinux/base:20240227@sha256:369753d82cfddfb500e9ef756334e0323508172c31041ea30501530cb5b24c12
ENV TERM=xterm

# Check the current system
RUN grep "VERSION\|ID" /etc/os-release

# Install system updates and dependencies
RUN pacman -Syu --noconfirm git netcat

# Download and execute the script
RUN /bin/bash -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
