# syntax=docker/dockerfile:1
FROM manjarolinux/base:20240227@sha256:369753d82cfddfb500e9ef756334e0323508172c31041ea30501530cb5b24c12
ENV TERM=xterm

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt

# Check the current environment
RUN uname -a \
  && { if [ -f /etc/os-release ]; then \
      cat /etc/os-release; \
    elif [ -f /etc/lsb-release ]; then \
      cat /etc/lsb-release; \
    fi; } \
  && df -h \
  && free -m \
  && date -u

# Install system updates and dependencies
RUN curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | xargs pacman -Sy --noconfirm \
  && pacman -Sy --noconfirm netcat

# Download and execute the script
RUN /bin/bash -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
