# syntax=docker/dockerfile:1
FROM opensuse/leap:15.5
ENV TERM=xterm

# Check the current system
RUN grep "VERSION\|ID" /etc/os-release

# Install system updates and dependencies
RUN zypper refresh \
  && zypper --non-interactive install bash curl git netcat

# Execute the script
#RUN mount -o remount,exec /tmp
RUN git clone --single-branch --depth 1 https://github.com/bitcoin-tools/nodebuilder.git \
  && cd nodebuilder
COPY nodebuilder /opt/src/scripts/nodebuilder
RUN /bin/bash -x /opt/src/scripts/nodebuilder
