# syntax=docker/dockerfile:1
# RHEL UBI is an enterprise-grade Linux distribution with long-term support.
# This Dockerfile is ideal for enterprise applications requiring strong support and stability.
FROM redhat/ubi8:latest@sha256:83068ea81dd02717b8e39b55cdeb2c1b2c9a3db260f01381b991755d44b15073
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument
ARG NODEBUILDER_VERSION=v1.4.0

# Define the nodebuilder URL
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies/runtime_dependencies_dnf.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies
RUN dnf makecache \
  && curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | xargs dnf --assumeyes install \
  && dnf clean all

# Download and execute the script
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
