# Use the FreeBSD base image
FROM freebsd:latest

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (e.g., master) as an argument.
ARG NODEBUILDER_VERSION=v1.7.1

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && sysctl -a | grep -i mem \
  && date -u

# Install wget dependency.
#RUN pkg update \
#  && pkg install -y wget \
#  && pkg clean -a

# Download and execute the script.
RUN wget ${NODEBUILDER_URL} \
  && chmod u+x nodebuilder \
  && ./nodebuilder
