# syntax=docker/dockerfile:1
# openSUSE is a robust Linux distribution that offers a great balance of stability and modernity.
# This Dockerfile is ideal for users seeking a reliable, versatile operating system.
FROM opensuse/tumbleweed:latest@sha256:16c407fb72851523804d9a122414e51ffde1ae7634284e7ea501c87587b32fad

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.12.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

ARG CI=false

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies.
RUN zypper refresh && zypper --non-interactive install findutils

# Download and execute the script.
RUN CI=${CI} /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
