# syntax=docker/dockerfile:1
# openSUSE is a robust Linux distribution that offers a great balance of stability and modernity.
# This Dockerfile is ideal for users seeking a reliable, versatile operating system.
FROM opensuse/tumbleweed:latest@sha256:eb4babd3fcc5fd36cd2f8ad8888c81c76e981d6188f3d3d45885a850959a5f73

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.10.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies.
RUN zypper refresh && zypper --non-interactive install findutils

# Download and execute the script.
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
