# syntax=docker/dockerfile:1
# Debian is the foundation of countless other distributions, including Ubuntu and Linux Mint.
# This Dockerfile is ideal for users who want a stable, secure, and lightweight environment.
FROM debian:stable-slim@sha256:2b2e35d67c8fda0ba853d40cd18e57b99ab12d82fd3200607015eb09784068bd

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.5.0-beta

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Download and execute the script.
RUN wget "${NODEBUILDER_URL}" && \
  chmod u+x "$(basename "${NODEBUILDER_URL}")" && \
  /bin/sh -c "./$(basename "${NODEBUILDER_URL}")"
