# syntax=docker/dockerfile:1
# Rocky Linux: An enterprise-grade operating system designed as a direct replacement for CentOS.
# This Dockerfile is a good choice for modern and resource-rich environments.
FROM rockylinux:9@sha256:d7be1c094cc5845ee815d4632fe377514ee6ebcf8efaed6892889657e5ddaaa6

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.7.1

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install sudo dependency.
RUN dnf makecache \
  && dnf --allowerasing --assumeyes install 'sudo' wget \
  && dnf clean all

# Download and execute the script.
RUN wget ${NODEBUILDER_URL} \
  && chmod u+x nodebuilder \
  && ./nodebuilder
