# syntax=docker/dockerfile:1
# Rocky Linux: An enterprise-grade operating system designed as a direct replacement for CentOS.
# This Dockerfile is a good choice for modern and resource-rich environments.
FROM rockylinux:9@sha256:c944604c0c759f5d164ffbdf0bbab2fac582b739938937403c067ab634a0518a
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument
ARG NODEBUILDER_VERSION=v1.4.0

# Define the nodebuilder URL
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies/runtime_dependencies_dnf.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies
RUN dnf makecache \
  && dnf --assumeyes remove curl-minimal \
  && dnf ---assumeyes install curl \
  && curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | xargs dnf --assumeyes install \
  && dnf clean all

# Download and execute the script
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
