# syntax=docker/dockerfile:1
# RHEL UBI is an enterprise-grade Linux distribution with long-term support.
# This Dockerfile is ideal for enterprise applications requiring strong support and stability.
FROM redhat/ubi9:latest@sha256:b68c21b2dd3e72abcf2f8dcfc77580e4030564d1243bfcb7cd64ccc5aa3e0a25

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.12.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/resources/dependencies/runtime_dependencies_dnf.txt

ARG CI=false

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install sudo dependency.
RUN dnf makecache \
  && dnf --allowerasing --assumeyes install 'sudo' wget \
  && dnf clean all

# Download and execute the script.
RUN wget ${NODEBUILDER_URL} \
  && chmod u+x nodebuilder \
  && CI=${CI} ./nodebuilder
