# syntax=docker/dockerfile:1
# EndeavourOS is a user-friendly Arch Linux based distro.
# This Dockerfile is ideal for users who want the power of Arch with more convenience.
FROM endeavouros/base:latest
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument
ARG NODEBUILDER_VERSION=v1.4.0

# Define the nodebuilder URL
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies/runtime_dependencies_pacman.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies
RUN curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | xargs pacman -Sy --noconfirm

# Download and execute the script
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
