# syntax=docker/dockerfile:1
# openSUSE is a robust Linux distribution that offers a great balance of stability and modernity.
# This Dockerfile is ideal for users seeking a reliable, versatile operating system.
FROM opensuse/leap:latest@sha256:79ea90d85d64c37a0985281f405f3336ac199f5ed1a041108472d248c03851d8

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.7.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Download and execute the script.
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
