# syntax=docker/dockerfile:1
# Manjaro focuses on user-friendliness and accessibility.
# This Dockerfile is ideal for users who want a balance of control and convenience.
FROM manjarolinux/base:latest@sha256:1efb6b368c4cf328d132f432dc50f7bb222156d9740718f85961e1dc5c65c515

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.5.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Download and execute the script.
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
