# syntax=docker/dockerfile:1
# Gentoo is known for its customization, optimization at the expense of image build time.asdf
# This Dockerfile offers a stable base image but takes extra time to compile all dependencies.
FROM gentoo/stage3:latest@sha256:353f7a19009fe0328496b9f16f6309c2ea7f04074e74972553e1bcc5f70015be

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.10.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Create the ebuild repository directory.
RUN [ -d /var/db/repos/gentoo/ ] || mkdir -p /var/db/repos/gentoo/

# Download and execute the script.
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
