# syntax=docker/dockerfile:1
# Amazon Linux is a Linux server operating system from AWS, optimized for EC2.
# This Dockerfile is ideal for applications that are deployed on AWS and require seamless integration.
FROM amazonlinux:latest@sha256:5fe11d17e56571a26e20df3fa1493bdf9139fb9f2cb6d84fad13104c7b869217

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.9.1

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install dependencies.
RUN dnf makecache \
  && dnf --allowerasing --assumeyes install findutils gnupg2 'sudo' wget \
  && dnf clean all

# Download and execute the script.
RUN wget ${NODEBUILDER_URL} \
  && chmod u+x nodebuilder \
  && ./nodebuilder
