# syntax=docker/dockerfile:1
# openSUSE is a robust Linux distribution that offers a great balance of stability and modernity.
# This Dockerfile is ideal for users seeking a reliable, versatile operating system.
FROM opensuse/leap:latest@sha256:10cc6a8e5b0d0063d8975b1421f2006d93c9a3f01563fb8e1f95183ffa4e772b

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.10.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Download and execute the script.
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
