# syntax=docker/dockerfile:1
# Oracle Linux is known for its robustness and performance.
# This Dockerfile is a good choice for modern and resource-rich environments.
FROM oraclelinux:9@sha256:b6d144cca39c0893f47f101b30e4c1f96a7413e3da365ec8c0fc7402576c3a1b

# Set the terminal type to Xterm.
ENV TERM=xterm

# Define the default version of nodebuilder or pass in a different version (eg master) as an argument.
ARG NODEBUILDER_VERSION=v1.6.0

# Define the nodebuilder URL.
ARG NODEBUILDER_URL=https://github.com/bitcoin-tools/nodebuilder/raw/${NODEBUILDER_VERSION}/nodebuilder

# Check the current environment.
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Download and execute the script.
RUN /bin/sh -c "$(curl -fsSL ${NODEBUILDER_URL} )"
