# syntax=docker/dockerfile:1
# RHEL UBI is an enterprise-grade Linux distribution with long-term support.
# This Dockerfile is ideal for enterprise applications requiring strong support and stability.
FROM registry.access.redhat.com/ubi8/ubi:8.9@sha256:edc34f89cf9c818c2fb28b8ea1780f384db563ce4293dc0ab8e73ec01791e5af
ENV TERM=xterm

# Define the  dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies
RUN dnf makecache \
  && dnf --assumeyes install libxcb-devel \
  && curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | xargs dnf --assumeyes install \
  && dnf clean all

# Download and execute the script
RUN /bin/sh -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
