# syntax=docker/dockerfile:1
# Google's Container-Optimized OS (COS) is designed specifically for running Docker containers on Google Cloud.
# This Dockerfile is ideal for applications deployed on Google Cloud that require an OS tailored for containerized applications.
FROM gcr.io/cos-cloud/cos-stable
ENV TERM=xterm

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies
RUN dnf makecache \
  && curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | xargs dnf --assumeyes install \
  && dnf clean all

# Download and execute the script
RUN /bin/sh -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
