# syntax=docker/dockerfile:1
# Amazon Linux is a Linux server operating system from AWS, optimized for EC2.
# This Dockerfile is ideal for applications that are deployed on AWS and require seamless integration.
FROM amazonlinux:2023
ENV TERM=xterm

# Define the dependencies URL
ARG DEPENDENCIES_URL=https://github.com/bitcoin-tools/nodebuilder/raw/master/dependencies.txt

# Check the current environment
RUN uname -a \
  && cat /etc/os-release \
  && df -h \
  && grep Mem /proc/meminfo \
  && date -u

# Install system updates and dependencies
RUN dnf makecache \
  && dnf --allowerasing --assumeyes install findutils libxcb-devel \
  && curl --fail --silent --show-error --location "${DEPENDENCIES_URL}" \
  | awk '{if ($0 == "gnupg") print "gnupg2"; else print $0;}' \
  | xargs dnf --allowerasing --assumeyes install \
  && dnf clean all

# Download and execute the script
RUN /bin/sh -c "$(curl -fsSL https://github.com/bitcoin-tools/nodebuilder/raw/master/nodebuilder)"
