# This is the configuration file for the pyspelling spell check job in the Validation CI workflow.

matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
  dictionary:
    wordlists:
    - data/pyspelling.wordlist.txt
    encoding: utf-8
  sources:
  - '**/*.md'
  - '.github/ISSUE_TEMPLATE/*.md'
  default_encoding: utf-8
