# syntax=docker/dockerfile:1
FROM fedora:39
ENV TERM=xterm

# Install system updates and dependencies
RUN dnf --assumeyes install ca-certificates curl git netcat 'sudo' \
  && rm -rf /var/lib/apt/lists/*

# Execute the script
RUN update-ca-certificates \
  && git clone --single-branch --depth 1 https://github.com/bitcoin-tools/nodebuilder.git \
  && cd nodebuilder
COPY nodebuilder /opt/src/scripts/nodebuilder
RUN ["/bin/bash", "-c", "/opt/src/scripts/nodebuilder"]
