# syntax=docker/dockerfile:1
FROM manjarolinux/base:20240227
ENV TERM=xterm

# Install system updates and dependencies
RUN pacman -Syu --noconfirm ca-certificates curl git netcat 'sudo'

# Execute the script
RUN update-ca-certificates \
  && git clone --single-branch --depth 1 https://github.com/bitcoin-tools/nodebuilder.git \
  && cd nodebuilder
COPY nodebuilder /opt/src/scripts/nodebuilder
RUN ["/bin/bash", "-c", "/opt/src/scripts/nodebuilder"]
